import type { RumbleBaseline } from "./types";

export const RUMBLE_BASELINE: RumbleBaseline = {
  version: 3,
  generatedAt: "2026-09-30T20:47:09.621Z",
  channels: [
    {
      id: "ajn-alex-jones-show",
      network: "ajn",
      name: "Alex Jones Show",
      url: "https://rumble.com/c/TheAlexJonesShowLive",
    },
    {
      id: "ajn-war-room",
      network: "ajn",
      name: "War Room with Harrison Smith",
      url: "https://rumble.com/c/WarRoomRumble",
    },
    {
      id: "ajn-alex-jones-network-live",
      network: "ajn",
      name: "Alex Jones Network Live",
      url: "https://rumble.com/c/AlexJonesNetworkLive",
    },
    {
      id: "ajn-network-feed",
      network: "ajn",
      name: "AJNLive (AJNetworkFeed)",
      url: "https://rumble.com/c/AJNetworkFeed",
    },
    {
      id: "ajn-alex-jones-show-rumble",
      network: "ajn",
      name: "The Alex Jones Show (Rumble)",
      url: "https://rumble.com/c/TheAlexJonesShowRumble",
    },
    {
      id: "rav-real-americas-voice",
      network: "rav",
      name: "Real America's Voice",
      url: "https://rumble.com/user/RealAmericasVoice",
    },
    {
      id: "rav-bannons-war-room",
      network: "rav",
      name: "Bannon's War Room",
      url: "https://rumble.com/c/BannonsWarRoom",
    },
    {
      id: "news-redacted",
      network: "other",
      name: "Redacted News",
      url: "https://rumble.com/c/Redacted",
    },
    {
      id: "news-newsmax",
      network: "other",
      name: "NEWSMAX",
      url: "https://rumble.com/c/NewsmaxTV",
    },
    {
      id: "news-rt",
      network: "other",
      name: "RT",
      url: "https://rumble.com/c/RTNews",
    },
    {
      id: "news-owen-shroyer",
      network: "other",
      name: "Owen Shroyer",
      url: "https://rumble.com/c/Owen",
    },
    {
      id: "news-lfa-tv",
      network: "other",
      name: "LFA TV",
      url: "https://rumble.com/c/LFATV",
    },
    {
      id: "news-vivafrei",
      network: "other",
      name: "vivafrei",
      url: "https://rumble.com/user/vivafrei",
    },
    {
      id: "news-rsbn",
      network: "other",
      name: "Right Side Broadcasting Network",
      url: "https://rumble.com/c/RSBN",
    },
    {
      id: "news-white-house",
      network: "other",
      name: "The White House",
      url: "https://rumble.com/c/whitehouse",
    },
    {
      id: "news-badlands",
      network: "other",
      name: "Badlands Media",
      url: "https://rumble.com/c/BadlandsMedia",
    },
  ],
  items: [
    {
      channelId: "ajn-alex-jones-show",
      videoId: "v7eh2s2",
      embedId: "v7capuk",
      title: "Alex Jones Live",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/da/s8/1/0/N/g/A/0NgAA.OvCc-small-Alex-Jones-Live..jpg",
      publishedAt: null,
      startedAt: "2026-08-21T17:13:55.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 3340,
    },
    {
      channelId: "ajn-alex-jones-network-live",
      videoId: "v7fnvu2",
      embedId: "v7dhiwk",
      title: "ALEX JONES NETWORK LIVE - THERE'S A WAR ON FOR YOUR MIND!",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/72/s8/1/g/m/w/n/gmwnA.OvCc-small-ALEX-JONES-NETWORK-LIVE-THE..jpg",
      publishedAt: null,
      startedAt: "2026-09-18T14:18:57.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 844,
    },
    {
      channelId: "ajn-network-feed",
      videoId: "v7fbep2",
      embedId: "v7d51rk",
      title: "War Room Live: Russia Tells NATO To Back Off Kaliningrad Or There Will Be Hell To Pay, Terrorist Co-Pilot Stabs Captain On Jet Bound For Israel, Iran/US Peace Talks Move Forward & Much More!",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/c6/s8/1/M/O/W/W/MOWWA.OvCc.1-small-LIVE-Emergency-Broadcast-Ir..jpg",
      publishedAt: null,
      startedAt: "2026-09-10T05:40:38.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 532,
    },
    {
      channelId: "ajn-alex-jones-show-rumble",
      videoId: "v7g3puq",
      embedId: "v7dxcx8",
      title: "The Alex Jones Show WEDNESDAY LIVE SHOW STREAM 9/30/26",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fwe2/b3/s8/6/I/g/Z/1/IgZ1A.OvCc.16r.jpg",
      publishedAt: null,
      startedAt: "2026-09-28T15:39:32.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 180,
    },
    {
      channelId: "rav-real-americas-voice",
      videoId: "v7g6mii",
      embedId: "v7e09l0",
      title: "HOME OF REAL NEWS & HONEST VIEWS",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fwe2/bd/s8/1/6/n/u/2/6nu2A.OvCc-small-HOME-OF-REAL-NEWS-and-HONES..jpg",
      publishedAt: null,
      startedAt: "2026-09-30T09:33:28.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 2410,
    },
    {
      channelId: "news-redacted",
      videoId: "v7g7f18",
      embedId: "v7e123q",
      title: "Hijacking False Flag!? Right As Netanyahu Predicts New Attacks On Israelis, America Leaves Iraq",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/99/s8/1/C/p/D/2/CpD2A.OvCc.1-small-Hijacking-False-Flag-Right-..jpg",
      publishedAt: null,
      startedAt: "2026-09-30T19:44:26.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 6330,
    },
    {
      channelId: "news-newsmax",
      videoId: "v60552h",
      embedId: "v5xwnen",
      title: "NEWSMAX2 LIVE | Real News for Real People",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/s8/1/P/d/4/O/Pd4Ov.OvCc.i-small-NEWSMAX2-LIVE-Real-News-for..jpg",
      publishedAt: null,
      startedAt: "2024-12-17T11:26:00.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 632,
    },
    {
      channelId: "news-rt",
      videoId: "v35waq4",
      embedId: "v33aw1a",
      title: "RT News | Livestream 24/7",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/cwg9/s8/1/m/9/W/z/m9Wzl.OvCc-small-RT-News-Livestream-247.jpg",
      publishedAt: null,
      startedAt: "2023-08-09T09:30:42.000Z",
      durationSec: null,
      kind: "continuous_live",
      state: "live",
      viewers: 484,
    },
    {
      channelId: "news-owen-shroyer",
      videoId: "v7g7f4w",
      embedId: "v7e127e",
      title: "Senate Votes To Cover Up Deaths of US Citizens In West Bank",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/3d/s8/1/8/r/2/Z/8r2ZA.OvCc-small-Trump-Approval-Rating-Hits-..jpg",
      publishedAt: null,
      startedAt: "2026-09-30T20:03:38.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 1110,
    },
    {
      channelId: "news-lfa-tv",
      videoId: "v7g6732",
      embedId: "v7dzu5k",
      title: "LIVE & BREAKING NEWS! | WEDNESDAY 9/30/26",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fwe2/08/s8/1/E/v/p/2/Evp2A.OvCc.6-small-LIVE-and-BREAKING-NEWS-WEDN..jpg",
      publishedAt: null,
      startedAt: "2026-09-30T11:21:40.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 776,
    },
    {
      channelId: "news-vivafrei",
      videoId: "v7g7cya",
      embedId: "v7e100s",
      title: "Brian Cole Jr. \"Confession\" Released - It is PURE ABUSE; Candace Ownes Sued for Defamation AND MORE!",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/81/s8/6/s/L/C/2/sLC2A.OvCc.r.jpg",
      publishedAt: null,
      startedAt: "2026-09-30T19:08:07.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 759,
    },
    {
      channelId: "news-white-house",
      videoId: "v7g7dps",
      embedId: "v7e10sa",
      title: "President Trump Makes an Announcement with the Secretary of Commerce",
      thumbnailUrl: "https://hugh.cdn.rumble.cloud/video/fww1/59/s8/6/W/0/C/2/W0C2A.OvCc.4.jpg",
      publishedAt: null,
      startedAt: "2026-09-30T20:25:53.000Z",
      durationSec: null,
      kind: "live",
      state: "live",
      viewers: 714,
    },
  ],
};
