// Daily News Digest in the Radio view: ticker + briefing. Headlines and links only; nothing here plays media.
import { useMemo, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import type { DigestView } from '../hooks/useDigest';
import { digestNotice, type DigestItem } from '../utils/newsDigest';

function timeLabel(iso: string | null): string {
  if (!iso) return '';
  const date = new Date(iso);
  return Number.isNaN(date.getTime()) ? '' : date.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
}

export function NewsTicker({ news }: { news: DigestView }) {
  const items = news.data?.digest.top ?? [];
  if (!items.length) return null;
  const row = (suffix: string) => items.map(item => (
    <a key={`${item.id}${suffix}`} className="ajr-ticker-item" tabIndex={suffix ? -1 : undefined} href={item.url} target="_blank" rel="noopener noreferrer"><b>{item.source}</b>{item.title}</a>
  ));
  return (
    <div className="ajr-ticker" role="region" aria-label="News headlines">
      <span className="ajr-ticker-label">NEWS</span>
      <div className="ajr-ticker-window"><div className="ajr-ticker-track">{row('')}<span aria-hidden="true" className="ajr-ticker-copy">{row('-copy')}</span></div></div>
    </div>
  );
}

function renderStory(item: DigestItem) {
  return (
    <a key={item.id} className="ajr-news-card" href={item.url} target="_blank" rel="noopener noreferrer" data-testid="digest-story">
      {item.imageUrl && <img className="ajr-news-thumb" src={item.imageUrl} alt="" loading="lazy" referrerPolicy="no-referrer" onError={event => { event.currentTarget.style.display = 'none'; }} />}
      <span className="ajr-news-body">
        <span className="ajr-news-meta">{item.source.toUpperCase()}{item.publishedAt ? ` · ${timeLabel(item.publishedAt)}` : ''}</span>
        <span className="ajr-news-title">{item.title}<ArrowUpRight size={14} aria-hidden="true" /></span>
        {item.excerpt && <span className="ajr-news-excerpt">{item.excerpt}</span>}
      </span>
    </a>
  );
}

export function DailyBriefing({ news }: { news: DigestView }) {
  const [source, setSource] = useState<string | null>(null);
  const digest = news.data?.digest ?? null;
  const items = useMemo(() => !digest ? [] : source ? digest.bySource.find(group => group.source === source)?.items ?? [] : digest.top, [digest, source]);
  const notice = digest ? digestNotice(digest.updatedAt, Date.now(), news.data?.status === 'error' ? news.data.error : null) : null;
  return (
    <section className="ajr-section ajr-news" id="ajr-news" aria-label="Daily briefing">
      <div className="ajr-heading"><div><div className="ajr-label">{digest?.date ? `THE DAILY BRIEFING · ${digest.date}` : 'THE DAILY BRIEFING'}</div><h2>Read the <em>news.</em></h2></div></div>
      {news.phase === 'loading' && <p className="ajr-status" role="status">Loading news…</p>}
      {news.phase === 'error' && <p className="ajr-status ajr-status-error" role="alert">The Daily Digest could not be loaded ({news.error}).</p>}
      {notice && <p className={`ajr-status ajr-status-${notice.level}`} role="status" title={digest?.updatedAt ?? undefined}>{notice.text}</p>}
      {digest && <>
        {digest.briefing.length > 0 && (
          <ol className="ajr-briefing" aria-label="Today's briefing">
            {digest.briefing.map((block, index) => (
              <li key={`${index}-${block.headline}`} className="ajr-briefing-item" data-testid="briefing-block">
                <span className="ajr-label">{String(index + 1).padStart(2, '0')}{block.source ? ` · ${block.source.toUpperCase()}` : ''}{block.theme ? ` · ${block.theme.toUpperCase()}` : ''}</span>
                <strong>{block.headline}</strong>
                {block.summary && <p>{block.summary}</p>}
              </li>
            ))}
          </ol>
        )}
        <div className="ajr-chips" role="group" aria-label="News sources">
          <button type="button" aria-pressed={source === null} className={`ajr-chip ${source === null ? 'selected' : ''}`} onClick={() => setSource(null)}>TOP STORIES</button>
          {digest.bySource.map(group => <button key={group.source} type="button" aria-pressed={source === group.source} className={`ajr-chip ${source === group.source ? 'selected' : ''}`} onClick={() => setSource(group.source)}>{group.source.toUpperCase()}</button>)}
        </div>
        {items.length === 0 && <p className="ajr-status" role="status">No stories from this source in the current digest.</p>}
        <div className="ajr-news-grid">{items.map(renderStory)}</div>
        <p className="ajr-fineprint">Headlines link to the original publishers. Briefing text is generated by the Daily News Digest.</p>
      </>}
    </section>
  );
}
